### ISSUE TITLE
the display strach

### ISSUE THREAD

**Issue by klokoleva** [OmarElGabry/Hashtegny#5] opened 2016-05-19 05:17 UTC
hi Omar,

the images from social main-post have strach images.
how to make the width used the percent (%) or decrease the amount for a row? 

thanks

**Comment by OmarElgabry** [comment] 2016-05-19 08:06
Hello,

You have two options here. Both ways allow you to control how many posts will be displayed in each row for different screen sizes.

**1. Using `percentPosition`**
Use `percentPosition` instead of `isFitWidth`. But, as I know, this option won't center your posts. You may play around and find if it's possible to center the posts or not, kindly check the [documentation](http://masonry.desandro.com/options.html).

``` js
// In hashtegny.js
var _options = {itemSelector: '.main-post', gutter: 10, percentPosition: true};
```

``` css
/* In main.grid.css */
.main-post {
    width: 20%;
}
@media screen and (max-width: 1024px) {
    .main-post{
        width: 40%;
    }
}
@media screen and (max-width: 480px) {
    .main-post{
        width: 100%;
    }
}
```

**2. Using `isFitWidth`(Default)**
Just use the default behavior and change the width of the post. This option will allow you to center your posts.

``` js
// In hashtegny.js
var _options = {itemSelector: '.main-post', gutter: 10, isFitWidth: true};
```

``` css
/* In main.grid.css */
.main-post {
    width: 400px;
}
@media screen and (max-width: 1024px) {
    .main-post{
        width: 300px;
    }
}
@media screen and (max-width: 480px) {
    .main-post{
        width: 280px;
    }
}
```

**Comment by klokoleva** [comment] 2016-05-19 11:01
hi Omar

I prefered used the percent option for the width. Thats great.
but the load first time need 3 sec into load. any tips to make the faster? 

thanks

**Comment by OmarElgabry** [comment] 2016-05-19 12:14
You can change the default behavoir for the posts to be displayed by default.

``` html
<!-- templates/default.html -->
<div class="main-post {{=post.network}} {{=post.post_type}}" date="{{=post.date}}">
```

But, the problem is that you need to call `$(targetEle).masonry(_options);` every time a post is appended to `targetEle`. You can check the [documentation](http://masonry.desandro.com/), and see if it's possible to re-initialize the plugin on the `targetEle` every time a new item or a post is added.

**Comment by OmarElgabry** [comment] 2016-05-26 06:38
I'll close this issue. If you faced any problems, or have more questions, you are welcome to open it again. Thanks.

**Closed as completed by OmarElgabry** 2016-05-26 06:38 UTC

**Comment by klokoleva** [comment] 2016-05-27 02:59
hi Omar, thanks for your advance. happy weekend !!!
